### PR TITLE
Feature: Curve25519 support

### PR DESCRIPTION
**Pull request by zapu**
This pull request introduces support for encryption/decryption with cv25519 keys. Encrypt+sign is also possible with ed25519+cv25519 keys. tweetnacl's scalarMult function is used for encryption, and tweetnacl's sign is used for signing - this functionality should probably by exposed in keybase-nacl, so it could be used instead of directly calling into tweetnacl.

There is also key generation included for cv25519, but it is not tested. EDDSA key generation is still missing, but I plan to work on it as well. Encryption/signatures were tested by exchanging various payloads between gpg2 (`gpg (GnuPG) 2.1.15, libgcrypt 1.7.3`) and KBPGP. There is also test file `tests/cv25519.iced` that does exactly that, but in unit testing fashion. 

Code details:

There is now a `Curve25519` class that extends `Curve`. It reads points in 0x40 format which encodes just X coordinate (regular `Curve` class expects format 0x4 and X, Y coordinates). The curve point here is just a Buffer - we do not deal with BigNumbers for points and scalars, it's all just buffers for us that we pass to tweetnacl. Because of that, the point operations were moved into the curve classes. ECDH can no longer, for example, do the encryption by getting G point from the curve and multiply it by scalar v - now it calls `curve.encrypt` instead, which for `Curve` is implemented using point multiplication, but for `Curve25519` it calls `tweetnacl.scalarMult`

Why not create a separate ECDH key classes, like ECDH25519 and have the scalarMults there, and leave Curve and ECDH alone? The issue is that cv25519 is the same public key algorithm type (`ECDH = 18`), and the 25519 only has its own curve OID. So to separate ECDH classes we would have to make either Parser.parse_public_key_mpis more complicated, or somewhere in ECDH key parsing suddenly return 25519 variants of the classes, which ruins the abstraction a little bit (calling Pair.parse should return instances of that Pair, not something different).

Let me know if it should be architected differently - the change itself is not very big, so I might as well apply it in a different way. Most of the work was figuring out how to make nacl pretend it's pgp.

Known issues:
- Curve.encrypt/decrypt method names are misleading, figure out better naming.
- Some code duplication, e.g. in Curve25519.mpi_from_buffer, (eddsa) Pair.pad_and_sign.

Related issues: #92 https://github.com/keybase/keybase-issues/issues/1738 https://github.com/keybase/keybase-issues/issues/2213

### CODE REVIEW

**Comment by maxtaco** [comment]
This looks great overall --- the one request I had would be to try to abstract multiplication in Curve25519 so that it can be done natively if there's a compiled version of sodium around.  I believe the function `crypto_scalarmult_curve25519` should do the trick, and wrappers can be introduced in `keybase-nacl` to expose scalar multiplication. What do you think?

**Comment by zapu** [comment]
OK, I'll look into `keybase-nacl` and try to export needed functions there. Thank you for going through my code :)

**Comment by zapu** [comment]
I made EDDSA Priv key use `keybase-nacl` - everything was already there, I just didn't look hard enough before. I'll work on `scalarmult` now.

**Comment by zapu** [comment]
Tell me if I understand this correctly - when I have keybase-nacl installed and built (I've witnessed it building sodium), and running `make test-server` in kbpgp, it should be using the compiled sodium. When I run `make test-browser` and run the script in browser, it will be running TweetNaCl.

So theoretically, doing both (test-server, and then using the browser script) tests should test both crypto code paths there?

I wonder if CI can somehow run different browsers and test there.

**Comment by maxtaco** [comment]
Yes you are correct and also that there isn't a good way to test this
automatically, yet....

**Comment by zapu** [comment]
Looks like sodium is not built when just `npm install kbpgp` is done. Is this by design?

```
(env) zapu@weakfox ~/sodium_test » npm install kbpgp                                                                                12:14:41
/home/zapu/sodium_test
└─┬ kbpgp@2.0.58 
  ├── bn@1.0.1 
  ├── bzip-deflate@1.0.0 
  ├── deep-equal@1.0.1 
  ├── iced-error@0.0.9 
  ├── iced-lock@1.1.0 
  ├── iced-runtime@1.0.3 
  ├── keybase-ecurve@1.0.0 
  ├─┬ keybase-nacl@1.0.9 
  │ └── uint64be@1.0.1 
  ├── minimist@1.2.0 
  ├── pgp-utils@0.0.30 
  ├── purepack@1.0.4 
  ├─┬ triplesec@3.0.25 
  │ ├── more-entropy@0.0.7 
  │ └── progress@1.1.8 
  └── tweetnacl@0.13.3 

npm WARN enoent ENOENT: no such file or directory, open '/home/zapu/sodium_test/package.json'
npm WARN sodium_test No description
npm WARN sodium_test No repository field.
npm WARN sodium_test No README data
npm WARN sodium_test No license field.
(env) zapu@weakfox ~/sodium_test » ls                                                                                               12:14:48
total 8,2k
drwxrwxr-x  8 zapu zapu 4,1k lis  1 12:14 env/
drwxrwxr-x 19 zapu zapu 4,1k lis  1 12:14 node_modules/
(env) zapu@weakfox ~/sodium_test » node                                                                                             12:14:50
> require('keybase-nacl')
{ sign: 
   { publicKeyLength: 32,
     secretKeyLength: 64,
     signatureLength: 64,
     seedLength: 32 },
  alloc: [Function] }
> require('keybase-nacl').alloc({})
TweetNaCl { ...
```

(with sodium built `alloc` returns `Sodium` object)

**Comment by maxtaco** [comment]
Yes this is by design. It has a lot of dependencies (like libtool) and
won't run via browserify.  But if you have it installed in your system it
will be picked up.

**Comment by zapu** [comment]
I see, thank you. Just trying making sure I'm actually running the code that I'm changing there.

I have the keybase-nacl and ecdh changes almost ready, I'll probably finish it and make the commits later in the day or tomorrow.

**Comment by zapu** [comment]
Still passes CI even though the test fails with `In reading /home/travis/build/keybase/kbpgp/test/files/cv25519.iced: TypeError: nacl.scalarmult is not a function`. I'm going to fix that.

**Comment by maxtaco** [comment]
Ok, I just pushed `keybase-nacl@1.0.10` to NPM

**Comment by zapu** [comment]
Looks like a bug in `iced-test` - when an exception occurs in unit test code, it propagates back to somewhere (didn't check exactly) and ends the script normally, instead of triggering an error. This line: https://github.com/maxtaco/iced-test/blob/master/index.iced#L144 should be in try-catch block. Should I make a fix?

**Comment by maxtaco** [comment]
Hmm, but the problem if that test is awaited, and the exception happens after the await, then the try-catch won't work.

**Comment by zapu** [comment]
If an exception happens after await, then it's an uncaught exception and this ends the node process with an error. But this does not seem to be the case in this log https://travis-ci.org/keybase/kbpgp/jobs/172594752

However, I could confirm the iced-test problem by adding some intentional error in one of the sync tests. When an exception happens in test, it propagates back to https://github.com/maxtaco/iced-test/blob/master/index.iced#L218 and it does not mark the failure. 

Looks like this is what happened in the CI as well, you can see the "In reading" string there (`In reading /home/travis/build/keybase/kbpgp/test/files/cv25519.iced: TypeError: nacl.scalarmult is not a function`). So somehow the decryption code runs all in one node tick, at least until the nacl call?

**Comment by maxtaco** [comment]
ah ok.  i wonder why the test process doesn't exit with status 1 if it crashes. let me look into that.

**Comment by zapu** [comment]
Sorry, I was wrong about the iced-test after all - the exception will trigger
```
✖ Failure due to test configuration issues
Tests: 233/234 passed
Makefile:94: recipe for target 'test-server' failed
```
at the end of testing, but it will skip entire file if a sync exception happens in one of the tests.

**Comment by zapu** [comment]
Also, could you try to refresh the build in CI? There should be a "Restart build" button on the right, if you are have rights to the repo. Thanks

**Comment by maxtaco** [comment]
Let me fix iced-test

**Comment by zapu** [comment]
Tell me if I'm wrong, but I don't see a way to currently generate cv25519 ECDH keys from the API. From what I've seen, the only way to specify the curve is by passing number of bits to `generate`. How should we approach this?

**Comment by maxtaco** [comment]
I think you're right, but check out `generate_ecc`, it calls into `generate` with suitable parameters.  I'm pretty sure this pattern will work here.

**Comment by zapu** [comment]
Still working on this. I've improved EDDSA, added key generation and serialization routines there. Key generation seems to work, with something like
```
primary = {
    flags: C.sign_data | C.certify_keys
    algo: kbpgp.ecc.EDDSA
}
subkeys = [{
    flags: C.encrypt_storage | C.encrypt_conn
    algo: kbpgp.ecc.ECDH
}]

await KeyManager.generate { userid: "Mr Robot", primary, subkeys }, defer err, alice
```

but the KeyManager is not able to encrypt and sign the message, because for some reason it chooses to use subkey for signing (or so I think: fails with `TypeError: _this.key.pad_and_sign is not a function
  at /home/zapu/pgp/kbpgp/lib/openpgp/packet/signature.js:278:21`).

I also tested cv25519 a bit more with a script that would:
1) Use gpg2 to generate Ed25519/Curve25519 keys.
2) Export the secret keys and import in kbpgp.
3) Encrypt and sign a message (it signs just fine with keys from gpg2).
4) Give the armored cipher to gpg2 to decrypt.
5) Decrypt with kbpgp for more verification.

And I've ran it a number of times and it looks like it's working.

**Comment by zapu** [comment]
Hmm... Looks like I could have just looked at `nacl/eddsa.iced` to see how to implement private key. Why there are two EDDSA implementations? Should I have not implemented the nacl eddsa stuff in `ecc/eddsa.iced` ?

**Comment by maxtaco** [comment]
Great work as always. A few things. With these parameters:

```coffeescript
subkeys = [{
    flags: C.encrypt_storage | C.encrypt_conn
    algo: kbpgp.ecc.ECDH
}]
```

You're likely getting the NIST curves.  I'm guessing you wanted Curve25519, so likely something else has to be done here.

As to the two implementations, what's in `nacl/eddsa.iced` and `nacl/dh.iced` is for "Keybase-style" signatures, which are entirely separate from GPG-style.  Keybase-style signatures are base64-encodings of msgpack structures.

**Comment by zapu** [comment]
Yes, I was getting the default p384 curve (I think - I don't have this open right now). What was weird, though, is that setting `flags` param to 0 was making something else confused, and kbpgp was trying to encrypt using the primary key (which was EDDSA), instead of the subkey. Calling `generate` with incorrect `flags` should fail (or should it?), but the manner in which it did was not obvious. I still haven't debugged this behavior, maybe I'm missing something and it's entirely something else.

I also started working on something that would allow people to use curve name instead of nbits, similarly to what gnupg allows in batch mode (e.g. `Subkey-Curve: Curve25519` in gpg2). I'll commit it once it's finished and we will see if it fits into KBPGP, because it would expand the API.

**Comment by maxtaco** [comment]
You're right it might very well be garbage-in, garbage-out.

Do you want to add these features and bugfixes in another PR and get this one merged?

**Comment by zapu** [comment]
Let me finish the curves and eddsa changes I'm doing and do tests for them and then we will see. Thanks!

**Comment by maxtaco** [comment]
ok great, thanks

**Comment by zapu** [comment]
Looks like the test fails because `make` does not build `src/ecc/eddsa.iced` and I haven't committed eddsa.js.

**Comment by zapu** [comment]
Let me know if generating keys with `curve_name` looks fine, I was trying to mimic gnupg a bit, but maybe there is a better solution.

**Comment by maxtaco** [comment]
Looks great to me, thanks for the great work here.

What would you like to do about the test.  Do you want me to merge your branch into a branch of mine, and then fix the tests?

**Comment by zapu** [comment]
I'm not sure what I did wrong there. When you look into the build log, it does not recompile the `eddsa.iced` or `curves.iced`.

```
...
node_modules/.bin/iced -I browserify -c -o `dirname lib/dsa.js` src/dsa.iced
node_modules/.bin/iced -I browserify -c -o `dirname lib/ecc/ecdsa.js` src/ecc/ecdsa.iced
node_modules/.bin/iced -I browserify -c -o `dirname lib/ecc/main.js` src/ecc/main.iced
node_modules/.bin/iced -I browserify -c -o `dirname lib/elgamal.js` src/elgamal.iced
...
```

Do all files pulled by git end up with the same date of modification, and that's why Makefile would skip some of them?

**Comment by maxtaco** [comment]
I was able to get it to build with `touch src/ecc/eddsa.iced && make`

**Comment by zapu** [comment]
Oh, it builds and passes the tests for me just fine, it's just a bit not deterministic on the CI side.

Or am I doing it wrong by not committing compiled files with every commit?

**Comment by maxtaco** [comment]
I would commit the built files too

**Comment by zapu** [comment]
OK - I'm a fan of small commits when working on a feature branch and only committing built assets on release, but it's not a problem to commit every time. Thanks!

**Comment by maxtaco** [comment]
Thank you @zapu, job well done!

**Comment by zapu** [comment]
Thank you for the merge :)

So, there is one issue relating to `flags` with key generation, should I look into that?

**Comment by maxtaco** [comment]
What was that issue?

**Comment by zapu** [comment]
As described in the issue https://github.com/keybase/kbpgp/pull/121#issuecomment-258877045 - basically, passing `flags: 0` to key generation will create a weird KeyManager which (in my case) tried to encrypt using primary key which was for signing only.

**Comment by maxtaco** [comment]
Ah, ok, thanks for reminding me.  Sure it makes sense to handle that bad input better...

**Pull request merged**
