### PR TITLE
Fix expiring keys in tests

### PR DESCRIPTION
**Pull request by zapu**
Some keys used for testing had expiration date. This PR is a result of using current date of year 2055 and running the tests, and then fixing all failures by making them use `now` argument wherever needed with the date when keys are still valid. The dates were determined by `git blame`.

By-products of that are fixes to few code-paths where `now` argument was not properly respected or not there at all:
* clear/detached signatures verification/signing
* import and unlock p3skb (although it supported `time_travel`)
* merge_pgp_private - but it's not tested enough

### CODE REVIEW

**Comment by maxtaco** [comment]
thank you doing this! seems like all the keys expired at the same time

**Comment by zapu** [comment]
It was just a few that were expiring yesterday, but I went ahead and fixed all of them by making `unix_timestamp` return date far ahead

**Comment by maxtaco** [comment]
ok thank you!

**Comment by zapu** [comment]
Thank you for +1, I'll have a fresh look tomorrow or day after to make sure it doesn't break anything and then merge.

**Pull request merged**
