### PR TITLE
v2.0.71 changelog

### PR DESCRIPTION
**Pull request by zapu**

### CODE REVIEW

**Comment by zapu** [comment]
cc @maxtaco can we do the release? thank you

**Comment by maxtaco** [comment]
Can you update the changelog for what's new in 2.0.71?

**Comment by zapu** [comment]
Thought it was just this one thing but it looks like there are also EdDSA fixes. I will add that.

**Comment by maxtaco** [comment]
ok, i cut a release and pushed to npm

**Comment by zapu** [comment]
Great, thank you!

**Pull request merged**
